OldGetMapName <- GetMapName

SpCoopMapTable <- {}
SpCoopMapTable["mp_coop_lobby_3"] <- "sp_a1_intro1"
SpCoopMapTable["mp_coop_start"] <- "sp_a1_intro1"
SpCoopMapTable["mp_coop_a1_intro2"] <- "sp_a1_intro2"
SpCoopMapTable["mp_coop_a1_intro3"] <- "sp_a1_intro3"
SpCoopMapTable["mp_coop_a1_intro4"] <- "sp_a1_intro4"
SpCoopMapTable["mp_coop_a1_intro5"] <- "sp_a1_intro5"
SpCoopMapTable["mp_coop_a1_intro5"] <- "sp_a1_intro5"
SpCoopMapTable["mp_coop_a1_intro6"] <- "sp_a1_intro6"
SpCoopMapTable["mp_coop_a1_intro7"] <- "sp_a1_intro7"
SpCoopMapTable["mp_coop_a1_wakeup"] <- "sp_a1_wakeup"
SpCoopMapTable["mp_coop_a2_intro"] <- "sp_a2_intro"
SpCoopMapTable["mp_coop_a2_laser_intro"] <- "sp_a2_laser_intro"
SpCoopMapTable["mp_coop_a2_laser_stairs"] <- "sp_a2_laser_stairs"
SpCoopMapTable["mp_coop_a2_dual_lasers"] <- "sp_a2_dual_lasers"
SpCoopMapTable["mp_coop_a2_laser_over_goo"] <- "sp_a2_laser_over_goo"
SpCoopMapTable["mp_coop_a2_catapult_intro"] <- "sp_a2_catapult_intro"
SpCoopMapTable["mp_coop_a2_trust_fling"] <- "sp_a2_trust_fling"
SpCoopMapTable["mp_coop_a2_pit_flings"] <- "sp_a2_pit_flings"
SpCoopMapTable["mp_coop_a2_fizzler_intro"] <- "sp_a2_fizzler_intro"
SpCoopMapTable["mp_coop_a2_sphere_peek"] <- "sp_a2_sphere_peek"
SpCoopMapTable["mp_coop_a2_ricochet"] <- "sp_a2_ricochet"
SpCoopMapTable["mp_coop_a2_bridge_intro"] <- "sp_a2_bridge_intro"
SpCoopMapTable["mp_coop_a2_bridge_the_gap"] <- "sp_a2_bridge_the_gap"
SpCoopMapTable["mp_coop_a2_turret_intro"] <- "sp_a2_turret_intro"
SpCoopMapTable["mp_coop_a2_laser_relays"] <- "sp_a2_laser_relays"
SpCoopMapTable["mp_coop_a2_turret_blocker"] <- "sp_a2_turret_blocker"
SpCoopMapTable["mp_coop_a2_laser_vs_turret"] <- "sp_a2_laser_vs_turret"
SpCoopMapTable["mp_coop_a2_pull_the_rug"] <- "sp_a2_pull_the_rug"
SpCoopMapTable["mp_coop_a2_column_blocker"] <- "sp_a2_column_blocker"
SpCoopMapTable["mp_coop_a2_laser_chaining"] <- "sp_a2_laser_chaining"
SpCoopMapTable["mp_coop_a2_triple_laser"] <- "sp_a2_triple_laser"
SpCoopMapTable["mp_coop_a2_bts1"] <- "sp_a2_bts1"
SpCoopMapTable["mp_coop_a2_bts2"] <- "sp_a2_bts2"
SpCoopMapTable["mp_coop_a2_bts3"] <- "sp_a2_bts3"
SpCoopMapTable["mp_coop_a2_bts4"] <- "sp_a2_bts4"
SpCoopMapTable["mp_coop_a2_bts5"] <- "sp_a2_bts5"
SpCoopMapTable["mp_coop_a2_bts6"] <- "sp_a2_bts6"
SpCoopMapTable["mp_coop_a2_core"] <- "sp_a2_core"
SpCoopMapTable["mp_coop_a3_01"] <- "sp_a3_01"
SpCoopMapTable["mp_coop_a3_03"] <- "sp_a3_03"
SpCoopMapTable["mp_coop_a3_jump_intro"] <- "sp_a3_jump_intro"
SpCoopMapTable["mp_coop_a3_bomb_flings"] <- "sp_a3_bomb_flings"
SpCoopMapTable["mp_coop_a3_crazy_box"] <- "sp_a3_crazy_box"
SpCoopMapTable["mp_coop_a3_transition01"] <- "sp_a3_transition01"
SpCoopMapTable["mp_coop_a3_speed_ramp"] <- "sp_a3_speed_ramp"
SpCoopMapTable["mp_coop_a3_speed_flings"] <- "sp_a3_speed_flings"
SpCoopMapTable["mp_coop_a3_portal_intro"] <- "sp_a3_portal_intro"
SpCoopMapTable["mp_coop_a3_end"] <- "sp_a3_end"
SpCoopMapTable["mp_coop_a4_intro"] <- "sp_a4_intro"
SpCoopMapTable["mp_coop_a4_tb_intro"] <- "sp_a4_tb_intro"
SpCoopMapTable["mp_coop_a4_tb_trust_drop"] <- "sp_a4_tb_trust_drop"
SpCoopMapTable["mp_coop_a4_tb_wall_button"] <- "sp_a4_tb_wall_button"
SpCoopMapTable["mp_coop_a4_tb_polarity"] <- "sp_a4_tb_polarity"
SpCoopMapTable["mp_coop_a4_tb_catch"] <- "sp_a4_tb_catch"
SpCoopMapTable["mp_coop_a4_stop_the_box"] <- "sp_a4_stop_the_box"
SpCoopMapTable["mp_coop_a4_laser_catapult"] <- "sp_a4_laser_catapult"
SpCoopMapTable["mp_coop_a4_laser_platform"] <- "sp_a4_laser_platform"
SpCoopMapTable["mp_coop_a4_speed_tb_catch"] <- "sp_a4_speed_tb_catch"
SpCoopMapTable["mp_coop_a4_jump_polarity"] <- "sp_a4_jump_polarity"
SpCoopMapTable["mp_coop_a4_finale1"] <- "sp_a4_finale1"
SpCoopMapTable["mp_coop_a4_finale2"] <- "sp_a4_finale2"
SpCoopMapTable["mp_coop_a4_finale3"] <- "sp_a4_finale3"
SpCoopMapTable["mp_coop_a4_finale4"] <- "sp_a4_finale4"

//SpCoopMapTable["modified_map_name"] <- "original_sp_map_name"


function GetMapName(){
  local mapName = OldGetMapName()
  if(SpCoopMapTable[mapName])mapName = SpCoopMapTable[mapName]
  return mapName
}

DoIncludeScript("choreo/glados",self.GetScriptScope())